add mypy ignore for referencing
causing errors:
/home/runner/.cache/pypoetry/virtualenvs/humanloop-3enmfHET-py3.9/lib/python3.9/site-packages/referencing/_core.py:565: error: Invalid "type: ignore" comment  [syntax]
/home/runner/.cache/pypoetry/virtualenvs/humanloop-3enmfHET-py3.9/lib/python3.9/site-packages/referencing/_core.py:566: error: Invalid "type: ignore" comment  [syntax]